-- 코드를 입력하세요
SELECT RI.REST_ID, RI.REST_NAME, RI.FOOD_TYPE, RI.FAVORITES, RI.ADDRESS, RS.SCORE
FROM REST_INFO AS RI, (SELECT REST_ID, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
                      FROM REST_REVIEW
                      GROUP BY REST_ID) AS RS
WHERE RI.REST_ID=RS.REST_ID AND RI.ADDRESS LIKE '서울%'
ORDER BY RS.SCORE DESC, RI.FAVORITES DESC